### ISSUE TITLE
Fabric issue 1.20.1

### ISSUE THREAD

**Issue by mrdiamondmanguydudeman** [axialeaa/Glissando#1]
No idea, just got this error message

Uncaught exception in thread "main"
java.lang.RuntimeException: Error parsing or using Mixin config glissando.mixins.json for mod glissando
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:96)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config glissando.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:168)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:121)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:108)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:98)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:94)
	... 3 more
Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_21 could not be set. Level is not supported by the active JRE or ASM version (Java 17.0, ASM 9.7.1 (ASM10_EXPERIMENTAL))
	at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1822)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:606)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:551)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:479)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1398)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:163)
	... 7 more

I don't know if i need to add more information

**Comment by axialeaa** [comment]
Thank you so much for reporting this!! It should be fixed in the next update if my diagnosis was accurate!

**Comment by WeRCrystalJems** [comment]
its not fixed yet i just got the same error screen pop up when is the next update?
Uncaught exception in thread "main"
java.lang.RuntimeException: Error parsing or using Mixin config beaconrange.mixins.json for mod beacon-range-extender
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:96)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:151)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: org.spongepowered.asm.launch.MixinInitialisationError: Error initialising mixin config beaconrange.mixins.json
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:168)
	at org.spongepowered.asm.mixin.Mixins.createConfiguration(Mixins.java:121)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:108)
	at org.spongepowered.asm.mixin.Mixins.addConfiguration(Mixins.java:98)
	at net.fabricmc.loader.impl.launch.FabricMixinBootstrap.init(FabricMixinBootstrap.java:94)
	... 3 more
Caused by: java.lang.IllegalArgumentException: The requested compatibility level JAVA_21 could not be set. Level is not supported by the active JRE or ASM version (Java 17.0, ASM 9.7.1 (ASM10_EXPERIMENTAL))
	at org.spongepowered.asm.mixin.MixinEnvironment.setCompatibilityLevel(MixinEnvironment.java:1822)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.initCompatibilityLevel(MixinConfig.java:606)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.postInit(MixinConfig.java:551)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.onLoad(MixinConfig.java:479)
	at org.spongepowered.asm.mixin.transformer.MixinConfig.create(MixinConfig.java:1398)
	at org.spongepowered.asm.mixin.transformer.Config.create(Config.java:163)
	... 7 more
I want to play 1.20.1

**Comment by axialeaa** [comment]
That appears to be a problem with beacon range extender, not glissando
